### ISSUE TITLE
resolve function not resolving from same library twice

### ISSUE THREAD

**Issue by jbizjak** [raml-org/webapi-parser#31]
In this example I have 5 files:

**test.raml:**
```
#%RAML 1.0
uses:
  Library: library.raml

/users/{id}:
  get:
    responses:
      200:
        body:
          application/json:
            type: Library.typeOne
```

**library.raml** and **types.raml** which are identical:
```
#%RAML 1.0 Library
types:
  typeOne: !include firstType.raml
  typeTwo: !include secondType.raml
```

**firstType.raml:**
```
#%RAML 1.0 DataType
uses:
  Types: types.raml
  Library: library.raml
type: object
properties:
  first:
    type: Types.typeTwo
  second:
    type: Library.typeTwo
```

**secondType.raml:**
```
#%RAML 1.0 DataType

type: object
properties:
  first: string
  last: string
```

I run the following code:
```
const model = await wap.raml10.parse(docPath)
const resApiModel = await wap.raml10.resolve(model)
console.log( resApiModel.encodes.endPoints[0].operations[0].responses[0].payloads[0].schema.toJsonSchema)
```

and get:
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$ref": "#/definitions/typeOne",
  "definitions": {
    "typeOne": {
      "type": "object",
      "additionalProperties": true,
      "required": [
        "first",
        "second"
      ],
      "properties": {
        "first": {
          "type": "object",
          "additionalProperties": true,
          "required": [
            "first",
            "last"
          ],
          "properties": {
            "first": {
              "type": "string"
            },
            "last": {
              "type": "string"
            }
          }
        },
        "second": {}
      }
    }
  }
}

```
Im wondering why the second property in typeOne is not resolved despite library.raml and types.raml being identical or if I am doing something incorrectly
