### ISSUE TITLE
Translating JSON "OneOf" to RAML DataTypes

### ISSUE THREAD

**Issue by HugaertsDries** [raml-org/webapi-parser#51]
I'm trying to translate the following JSON schema to a RAML datatype using the provided [tutorial](https://raml-org.github.io/webapi-parser/translating-json-raml.html). But it seems to fail parsing on the JSON "[OneOf](https://json-schema.org/understanding-json-schema/reference/combining.html#oneof)" keyword. Is this not yet supported?

Input JSON:
```
{
 "$schema" : "http://json-schema.org/draft-04/schema#",
 "title" : "Product",
 "type" : "object",
 "oneOf" : [ {
    "$ref" : "#/definitions/PromotionalProduct_-1109912719"
 }, {
    "$ref" : "#/definitions/DefaultProduct_-1835798300"
 } ],
 "id" : "#/definitions/Product_-1110706969"
}
```
output RAML:
```
  Product_-1110706969:
    displayName: Product
    type: object
    (amf-xone):
      - PromotionalProduct_-1109912719
      - DefaultProduct_-1835798300
```
