### ISSUE TITLE
Plain JSON schemas as Types

### ISSUE THREAD

**Issue by HugaertsDries** [raml-org/webapi-parser#57]
Is it possible to declare plain JSON schemas in the `WebApiDocument`?

I tried to achieve this using the `SchemaShape`, but the formatting seems off.

Thx in advance!

Example of code:
```
SchemaShape schema = new SchemaShape();
schema.withMediatype("application/json");
schema.withName(schemaName);
schema.withRaw(jsonSchema);

WebApi api = new WebApi()
WebApiDocument model = new WebApiDocument(api);
model.withDeclaredElement(schema)

```

Ouput:
```
types:
  CompositeTo_-570650100: "{\r\n  \"$schema\" : \"http://json-schema.org/draft-04/schema#\",\r\n  \"title\" : \"CompositeTo\",\r\n  \"type\" : \"object\",\r\n  \"properties\" : {\r\n    \"var\" : {\r\n      \"type\" : \"string\"\r\n    },\r\n    \"simple\" : {\r\n      \"$ref\" : \"#/definitions/SimpleTo_-2135181267\"\r\n    }\r\n  },\r\n  \"required\" : [ \"var\", \"simple\" ],\r\n  \"id\" : \"#/definitions/CompositeTo_-570650100\"\r\n}"
  CompositeTo_-510277817: "{\r\n  \"$schema\" : \"http://json-schema.org/draft-04/schema#\",\r\n  \"title\" : \"CompositeTo\",\r\n  \"type\" : \"object\",\r\n  \"properties\" : {\r\n    \"var\" : {\r\n      \"type\" : \"string\"\r\n    },\r\n    \"simple\" : {\r\n      \"$ref\" : \"#/definitions/SimpleTo_-1766103738\"\r\n    }\r\n  },\r\n  \"required\" : [ \"var\", \"simple\" ],\r\n  \"id\" : \"#/definitions/CompositeTo_-510277817\"\r\n}"
  SimpleTo_-2135181267: "{\r\n  \"$schema\" : \"http://json-schema.org/draft-04/schema#\",\r\n  \"title\" : \"SimpleTo\",\r\n  \"type\" : \"object\",\r\n  \"properties\" : {\r\n    \"bar\" : {\r\n      \"type\" : \"number\"\r\n    },\r\n    \"foo\" : {\r\n      \"type\" : \"string\"\r\n    },\r\n    \"baz\" : {\r\n      \"type\" : \"boolean\"\r\n    }\r\n  },\r\n  \"required\" : [ \"bar\", \"foo\", \"baz\" ],\r\n  \"id\" : \"#/definitions/SimpleTo_-2135181267\"\r\n}"
  SimpleTo_-1766103738: "{\r\n  \"$schema\" : \"http://json-schema.org/draft-04/schema#\",\r\n  \"title\" : \"SimpleTo\",\r\n  \"type\" : \"object\",\r\n  \"properties\" : {\r\n    \"bar\" : {\r\n      \"type\" : \"number\"\r\n    },\r\n    \"foo\" : {\r\n      \"type\" : \"string\"\r\n    },\r\n    \"baz\" : {\r\n      \"type\" : \"boolean\"\r\n    }\r\n  },\r\n  \"required\" : [ \"bar\", \"foo\", \"baz\" ],\r\n  \"id\" : \"#/definitions/SimpleTo_-1766103738\"\r\n}"


```
