### ISSUE TITLE
Types not transformed to from RAML to OAS correctly

### ISSUE THREAD

**Issue by BBartosz** [raml-org/webapi-parser#61]
I have problem like when transforming RAML10 into OAS20:

When i have raml file like following:

```yaml
#%RAML 1.0 DataType
description: Price Request
properties:
  passenger:
    type: array
    items: !include ../../common/numberType.raml
  someObject:
    type: !include someObject.raml
  inventoryObject:
    type: !include ../../common/inventoryObject.raml
```

it got expanded into swagger json like following (look at inventoryObject and someObject): 

```json
{
  "x-amf-fragmentType": "2.0 DataType",
  "description": "Price Request",
  "type": "object",
  "required": [
    "passenger",
    "flyBookItem",
    "inventoryControl"
  ],
  "properties": {
    "passenger": {
      "type": "array",
      "items": {
        "$ref": "../../common/numberType.json"
      }
    },
    "someObject": {
      "type": "object",
      "x-amf-merge": [
        {
          "$ref": "#/definitions/type"
        }
      ]
    },
    "inventoryObject": {
      "type": "object",
      "x-amf-merge": [
        {
          "$ref": "#/definitions/type"
        }
      ]
    }
  }
}
```

So when I have list of objects with referenced type to it then it can transform correctly. When i have object with specified typed as reference object get this:

```
...
"x-amf-merge": [
        {
          "$ref": "#/definitions/type"
        }
      ]
...
```

Do i specify my raml incorrectly? Im surprised nobody had this issue before because it looks like such a common use case. One more thing: when i use `.resolve()` on my model, then the objects are resolved correctly. But i dont want to resolve it because i want to generate code from my swagger so i dont want duplicate classes. So i would like to have kept references to other objects. SO this is swagger json i want:

```json
{
  "x-amf-fragmentType": "2.0 DataType",
  "description": "Price Request",
  "type": "object",
  "required": [
    "passenger",
    "flyBookItem",
    "inventoryControl"
  ],
  "properties": {
    "passenger": {
      "type": "array",
      "items": {
        "$ref": "../../common/numberType.json"
      }
    },
    "someObject": {
      "type": "object",
      "x-amf-merge": [
        {
          "$ref": "../../common/numberType.raml"
        }
      ]
    },
    "inventoryObject": {
      "type": "object",
      "x-amf-merge": [
        {
          "$ref": "../../common/inventoryObject.raml"
        }
      ]
    }
  }
}
```
